### PR TITLE
Info about newcomer dinner & transportation, remove list of 2017 places

### PR DESCRIPTION
**Pull request by ranti**

### CODE REVIEW

**Comment by ghost** [comment]
@ranti, /general-info/venues/index.html does not have `include_relative dinner.html`.  Did you mean to include this?  Also, when you do include dinner.html make sure to change h3 to h2 to match the other sections included in /general-info/venues

**Comment by ranti** [comment]
Thanks, @wallberg-umd; the additional changes are ready for re-review.

**Comment by ghost** [comment]
@ranti A minor thing, but the text in the Transportation box on the /general-info/venues page bleeds outside of the box on certain browser window widths.

**Comment by ranti** [comment]
@wallberg-umd noted. thanks. I will take a look into this again.

**Pull request merged**
