### PR TITLE
Adds Duty officers data and images

### PR DESCRIPTION
**Pull request by bibliotechy**
Adds dtaa file with duty officer details.

Also adds a section for Online Duty Officers.  Will need to be updated with their handles in future, but DO organizers would like their names on the website for now. 

Also updates a few details in the Duty Officer section regarding emails lists and anonymous form.

### CODE REVIEW

**Comment by ranti** [comment]
I'm currently reviewing it. Could you check if the anonymous online form is really working? I got an apache debian default page instead.

**Comment by bibliotechy** [comment]
The url for that was confirmed by the DO organizers. It will be activated very shortly. Is it worth commenting it out till it is live?

**Comment by ranti** [comment]
If it's going to be activated tomorrow, we could just publish it tonight. Otherwise, I suggest to comment it out for the time being.

**Comment by bibliotechy** [comment]
I don't know exactly when it will be activated, so I've commented it out. Will follow up will subsequent PR when I know it is active.

**Pull request merged**
