### PR TITLE
Issue 24

### LINKED ISSUE #24: HTML & CSS clean-up
There are a lot of unnecessary classes and and div nesting.

Also, I want to get rid of `.cell .cell-lg` as bootstrap already has built-in container functionality.

### LINKED ISSUE #28: header image not wide enough on larger screen
use `` instead of background image

### PR DESCRIPTION
**Pull request by queryluke**
NOTE: This has a new header as part of the HTML / CSS clean up, please review.

It should close #28 

And completes the first half of #24 

Once it's merged I'll close #24 and make a new issue for `<h#>` tags

### CODE REVIEW

**Comment by phette23** [comment]
Couple minor things: `a.btn-primary` buttons inside particular sections (3n + 1) now have a font color the same as their background, see for instance "Sponsor Code4Lib" button on "schedule/timeline.html"

We lost the (nice IMO) alternating background colors on "prospectus/index.html" in `section#targetedSponsorship` too. The CSS was `#targetedSponsorship .row:nth-child(even) .thumbnail { background-color: #fcb99b; }` so without `.row` it misses its mark.

These are both side effects of the HTML restructuring, I think.

**Comment by phette23** [comment]
I think the new header solves that contrast issue, too, btw. The button is nice & visible plus we'll be able to add text/buttons in that same row as needed.

**Comment by queryluke** [comment]
Thanks for catching those issues. I'll fix them in the AM (EST)

**Comment by phette23** [comment]
No problem. Sorry about introducing conflicts—I added just one sentence about PDF to prospectus so it should be easy to figure them out.

**Comment by queryluke** [comment]
No worries! Everything should be ready now

**Comment by phette23** [comment]
👍

**Pull request merged**
