### PR TITLE
Add toggles to open scholarship applications

### PR DESCRIPTION
**Pull request by mcalsada**
These are the initial changes for #85. This PR should be safe to merge now as these changes here are all controlled by toggles that are currently set to false. The toggle to open up scholarships (`diversity-scholarship-applications.show`) should be modified to true on October 16th. 

Some generic text was updated on the diversity scholarship page with new date/time/location for the conference. The scholarship committee will be providing @ranti updated text by October 13th which will replace some of the text changed here. 

- Added announcements section to pre-conference page for general announcements
- Added toggle for displaying call for applications for diversity scholarship
- Added toggle for displaying scholarship sponsors
- Added panel to scholarships page when diversity scholarship is open for applications
- Implemented toggles on diversity scholarship page

### CODE REVIEW

**Comment by phette23** [comment]
I did some basic content edits but I'm also thinking—does it make sense to have this pretty small stub under `general-info/scholarships` with all the main information under `diversity-scholarships`? Could we move the scholarships index content to just be on the general-info page? Right now it's just so tiny looking with links pointing elsewhere, makes more sense to me to reduce the number of locations that this content lives in.

**Comment by mcalsada** [comment]
That makes sense to me @phette23. I'll be away Friday-Monday and won't be able to make any changes. Maybe @ranti can integrate them with some of the other scholarship changes being planned?

**Comment by phette23** [comment]
OK so I took a shot at this, placing all the diversity scholarship information under the general-info folder and removing the old folder. I think it's cleaner to have all the info in one place with no splash page but someone else will have to check this PR too to make sure I didn't break any links, as the change is pretty large.

**Comment by queryluke** [comment]
I've reviewed it. Everything looks tip-top 👍

**Pull request merged**
