### PR TITLE
Disabling the donation link

### PR DESCRIPTION
**Pull request by mjingle**
Not sure if this should be done by removing code like I suggested or if changes elsewhere need to be made. Thanks!

### CODE REVIEW

**Comment by queryluke** [comment]
Looking at the code, the link only shows up if the `donate-link` isn't empty in the [config file](https://github.com/code4lib/2018.code4lib.org/blob/master/_data/conf.yml#L8). Do you want to keep this url in the config file? Possibly for archival or if you plan on opening it up in the future?

If you'd like to save the url, I can write a quick on/off toggle for the donations button.

Otherwise, the "preferred" (ugh...using this word makes me feel so slimy) solution would be to remove it in the config file, which will prevent the button from rendering.

**Comment by mjingle** [comment]
You can remove the URL from the config file. That should be fine. It leads to a payment portal hosted/facilitated by our contracted conference planners, Concentra. Thank you!

**Comment by queryluke** [comment]
It shall be done!

**Comment by mjingle** [comment]
Thank you! You're awesome!

**Pull request closed without merging**
